// ACTION TYPES OR CONSTANTS

export const REDUX_FORM_ERROR = "REDUX_FORM_ERROR";
export const SIGN_UP_USER = "SIGN_UP_USER";
export const SIGN_IN_USER = "SIGN_IN_USER";
export const SIGN_OUT_USER = "SIGN_OUT_USER";
